### ISSUE TITLE
음악 핀 검색 - 수정

### ISSUE THREAD

**Issue by Ravende** [EFUB4-Jukebox/songpin-frontend#17]
## Description
음악 핀 검색 페이지 디자인 변경 사항 수정

## To-do
- [x] 검색 페이지 - 결과 none일 때 띄울 메시지 추가
- [x] 검색창 placeholder 추가
- [x] 노래 제목 애니메이션 추가
- [x] 그 외 자잘한 수정 - 텍스트 한글 변경
- [x] 사이드바 컴포넌트 사용
- [x] 핀 컴포넌트 더보기-펼치기 사용
