### ISSUE TITLE
유저 검색 - 수정

### ISSUE THREAD

**Issue by yoonjin-C** [EFUB4-Jukebox/songpin-frontend#18]
## Description
유저 검색 페이지 퍼블리싱

## To-do
- [x] SideSection 컴포넌트 대체
- [x] 타 유저 플레이리스트 페이지 
- [x] 사이드바 적용
- [x] 핀 컴포넌트 더보기 반영

## ETC
