### ISSUE TITLE
플레이리스트 - 수정

### ISSUE THREAD

**Issue by yoonjin-C** [EFUB4-Jukebox/songpin-frontend#20]
## Description
플레이리스트 페이지 퍼블리싱

## To-do
- [x] SideSection 컴포넌트 대체
- [x] 플레이리스트 편집 페이지 퍼블리싱
- [x] 사이드바 적용
- [x] 더보기버튼 눌렀을때 팝업창 위치 수정

## ETC
