### ISSUE TITLE
통계 API 연결

### ISSUE THREAD

**Issue by YoungseoChoi23** [EFUB4-Jukebox/songpin-frontend#44]
## Description
소개 페이지 통계 api 연결

## To-do
- [x]  서비스 통계 종합 (올해 등록된 총 핀 개수, 가장 핀이 많이 등록된 노래, 가장 핀이 많이 등록된 장소, 가장 핀이 많이 등록된 장르)
- [x] 지도 좌표 이용해서 가장 핀이 많이 등록된 장소 이미지 추출
- [x]  서비스 통계 장르별 장소, 노래 (장르 별로 가장 많은 핀이 등록된 장소, 노래 정보를 전달)

## ETC
